01 = { path = "dt_01.jpg", caption = "Vamp hits KAT with a Facebuster.", source = "Official BWD page / Archive.org" }
02 = { path = "dt_02.jpg", caption = "Vamp and Kid Crusher.", source = "Official BWD page / Archive.org" }
03 = { path = "dt_03.jpg", caption = "KAT sets Vamp for a Piledriver.", source = "Official BWD page / Archive.org" }
04 = { path = "dt_04.jpg", caption = "Vamp vs Kid Crusher.", source = "Official BWD page / Archive.org" }
05 = { path = "dt_05.jpg", caption = "Vamp hits Kid Crusher with a Spinebuster.", source = "Official BWD page / Archive.org" }
06 = { path = "dt_06.jpg", caption = "Vamp wins.", source = "Official BWD page / Archive.org" }
07 = { path = "dt_07.jpg", caption = "KAT.", source = "Official BWD page / Archive.org" }
08 = { path = "dt_08.jpg", caption = "Kid Crusher.", source = "Official BWD page / Archive.org" }
09 = { path = "dt_09.jpg", caption = "Kid Crusher with Vamp in a hold.", source = "Official BWD page / Archive.org" }
10 = { path = "dt_10.jpg", caption = "Kid Crusher.", source = "Official BWD page / Archive.org" }
11 = { path = "dt_11.jpg", caption = "KAT.", source = "Official BWD page / Archive.org" }
13 = { path = "dt_13.jpg", caption = "Vamp jumps on Kid Crusher.", source = "Official BWD page / Archive.org" }
14 = { path = "dt_14.jpg", caption = "Kid Crusher jumps on KAT.", source = "Official BWD page / Archive.org" }
16 = { path = "dt_16.jpg", caption = "Vamp locks Kid Crusher in a Sharpshooter.", source = "Official BWD page / Archive.org" }
17 = { path = "dt_17.jpg", caption = "Vamp.", source = "Official BWD page / Archive.org" }
18 = { path = "dt_18.jpg", caption = "Kid Crusher chokes KAT.", source = "Official BWD page / Archive.org" }
