0001 = { path = "low2-logo.jpg", caption = "Official logo.", source = "Official Legacy Facebook" }
0002 = { path = "greg.webp", caption = "Image announcing [Greg](@/w/greg.md).", source = "Official Legacy Facebook" }
0003 = { path = "kubes.webp", caption = "Image announcing Kubes.", source = "Official Legacy Facebook" }
