001 = { path = "wjazd-na-rewir-plakat.webp", caption = "Official poster.", source = "Official PpW Facebook" }
002 = { path = "justin-joy-wraca.webp", caption = "Image announcing [Justin Joy](@/w/justin-joy.md).", source = "Official PpW Facebook" }
