01 = { path = "2025-01-25-ppw-gruba-przesada-plakat.jpg", caption = "Official poster.", source = "Official PpW Facebook" }
02 = { path = "svd-szkaluje-isnorra.jpg", caption = "Basically, [Dobroniak](@/w/stanislaw-van-dobroniak.md) says that Isnorr stinks.", source = "Official PpW Facebook" }
03 = { path = "dobroniak-dfw.jpg", caption = "[Dobroniak](@/w/stanislaw-van-dobroniak.md) with the front plate of the [DFW Championship](@/c/dfw-championship.md).", source = "Krzysztof Zych" }
04 = { path = "banana-chair.jpg", caption = "Banana chair.", source = "Krzysztof Zych" }
05 = { path = "banana-mannequin.jpg", caption = "Banana mannequin.", source = "Krzysztof Zych" }
06 = { path = "banana-table.jpg", caption = "Banana table.", source = "Krzysztof Zych" }
