0001 = { path = "mzw-green-madness-poster.webp", caption = "Official poster, featuring left to right: [Aron Wake](@/w/aron-wake.md), [Marcelito](@/w/marcelito.md) and [Goblin](@/w/goblin.md).", source = "Official MZW Facebook" }
