on:
  pull_request:
    types: [opened, synchronize]

name: New linter pipeline
jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        name: Install UV and Python
        with:
          version: latest
          python-version: "3.13.3"
          activate-environment: true
          enable-cache: true
      - name: Run guardians
        id: analysis
        run: |
          uv run make meta aliases
          uv run bin/guardian
      - name: Post review comments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO_PATH: ${{ github.repository }}
          REPORT_FILE: ${{ steps.analysis.outputs.report_file }}
        run: |
          PYTHONPATH=src uv run python src/bin/post_review.py
