# On every push this script is executed
on: push
name: Lint and verify metadata
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install pyyaml
      - name: checkout
        uses: actions/checkout@v4
      - name: build intermediate data
        run: |
          echo "::group::Building intermediate data"
          mkdir -p data
          bin/build_metadata.py
          bin/build_roster.py
          bin/build_matches.py
      - name: Lint content
        run: |
          bin/lint.py
